version: '3'
services:
  pyxdesktop:
    image: "postgres:latest" # use latest official postgres version
    environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: postgres
            POSTGRES_DB: desktop
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
  desktop:
    container_name: api
    restart: always
    build: .
    ports:
      - "3434:3434"
    depends_on:
      - pyxdesktop
volumes:
  database-data: # named volumes can be managed easier using docker-compose

